app/src/ui_stream.c, app/src/ui_stream_nbgl.c, tests/integration/stax/test_sign_execute_outbox_messages.py
fixes https://github.com/trilitech/ledger-app-tezos-wallet/issues/24
=> Stax: tap once to change screen

README.md, app/Makefile
=> app: support u2f interface

.github/workflows/build.yml, docker/Dockerfile.integration-tests, tests/integration/nanos/test_get_pk.sh, tests/integration/nanos/test_get_tz2_pk.sh, tests/integration/nanos/test_get_tz3_pk.sh, tests/integration/nanos/test_git.sh, tests/integration/nanos/test_unimplemented_commands.sh, tests/integration/nanos/test_version.sh, tests/integration/nanosp/test_get_pk.sh, tests/integration/nanosp/test_get_tz2_pk.sh, tests/integration/nanosp/test_get_tz3_pk.sh, tests/integration/nanosp/test_git.sh, tests/integration/nanosp/test_unimplemented_commands.sh, tests/integration/nanosp/test_version.sh, tests/integration/nanox/test_get_pk.sh, tests/integration/nanox/test_get_tz2_pk.sh, tests/integration/nanox/test_get_tz3_pk.sh, tests/integration/nanox/test_git.sh, tests/integration/nanox/test_unimplemented_commands.sh, tests/integration/nanox/test_version.sh, tests/integration/run_test_docker.sh, tests/integration/stax/test_get_pk.py, tests/integration/stax/test_git.py, tests/integration/stax/test_sign_transfer_without_hash.py, tests/integration/stax/test_unimplemented_commands.py, tests/integration/stax/test_version.py, tests/integration/stax/utils.py, tests/integration/test_runtime.sh
=> Tests: add test for all commands

app/src/apdu_pubkey.c, app/src/ui_stream.c, tests/integration/nanos/test_regression_continue_after_reject.sh, tests/integration/nanosp/test_regression_continue_after_reject.sh, tests/integration/nanox/test_regression_continue_after_reject.sh, tests/integration/stax/test_provide_pk_reject.py
=> Fix EXC_UNEXPECTED_STATE after rejection

Makefile, README.md, scripts/run_app.sh, tests/integration/app_vars.sh, tests/integration/test_runtime.sh
- add `format` target in Makefile
- add helper scripts for testing stax/resetting gold images + fix instructions for doing so
=> tooling: improvements to dev workflow

.github/workflows/swap.yml
See: https://github.com/spalmer25/app-exchange/pull/4
=> CI: update screens snapshots in swap tests according to PR 118

.github/workflows/swap.yml
See: https://github.com/functori/app-exchange/pull/3
=> CI: fix eth-app version in swap-tests

.github/workflows/swap.yml
fixes #133 
swap-tests branch: https://github.com/functori/app-exchange/pull/1
=> CI: Add swap stax test

ledger_app.toml
Required by Ledger. See https://github.com/LedgerHQ/ledgered/blob/master/doc/utils/manifest.md for more information
*NB* the tests section is optional. We leave it blank here since we don't use the reusable workflows for our tests.
=> wallet: add top-level ledger_app.toml file

.pre-commit-config.yaml, Makefile, app/src/parser/operation_parser.c, app/src/parser/operation_state.h, app/src/parser/parser_state.c, app/src/parser/parser_state.h, tests/unit/ctest/Makefile, tests/unit/ctest/ctest.h, tests/unit/ctest/digestif/LICENSE.md, tests/unit/ctest/digestif/bitfn.h, tests/unit/ctest/digestif/sha256.c, tests/unit/ctest/digestif/sha256.h, tests/unit/ctest/main.c, tests/unit/ctest/tests_parser.c
fixes #158 
This PR updates the parser to keep track of the complexity of the current operation field.
=> Add complex trait to operation fields

README.md, scripts/test_swap.sh
This PR add a script to ease swap tests snapshots update.
=> Swap: add a doc and a script to perform swap tests.

Makefile, app/src/apdu_sign.c, app/src/parser/operation_parser.c, app/src/parser/parser_state.c, app/src/parser/parser_state.h, tests/unit/ctest/tests_parser.c, tests/unit/parser/micheline_cparse_stubs.c
=> Add field index and create a grouped struct for field information.

.github/workflows/swap.yml, app/src/handle_swap.c
Corresponding PR: https://github.com/functori/app-exchange/pull/13
Fixes: #182
=> app: fix swap tests

app/src/handle_swap.c
=> Swap: do not check extra_id param anymore

app/src/handle_swap.c, app/src/parser/operation_parser.c, app/src/parser/operation_state.h
=> Swap: allow one reveal before the transaction

.github/workflows/swap.yml, app/src/apdu_pubkey.c, app/src/apdu_sign.c, app/src/app_main.c, app/src/globals.h, app/src/keys.c, app/src/ui_stream_nbgl.c, scripts/test_swap.sh
<test> - can we do away with the app-exchange fork?
=> CI: use default app-exchange repo

.github/workflows/swap.yml, app/src/apdu_pubkey.c, app/src/apdu_sign.c, app/src/app_main.c, app/src/globals.h, app/src/keys.c, app/src/ui_stream_nbgl.c
=> Dont update display while processing transactions called from swap.

.github/workflows/build.yml, Makefile, scripts/test_swap.sh
=> Tests: fix failing tests at app-builder version 3.15.0

app/src/parser/operation_parser.c
=> Add new Oxford2 entrypoints

Makefile, app/src/parser/parser_state.h
=> Test: fix failing tests at latest app builder version

app/src/apdu.h, app/src/apdu_sign.h, app/src/globals.h, app/src/handle_swap.h, app/src/keys.h, app/src/ui_commons.h, app/src/ui_home.c, app/src/ui_home.h, app/src/ui_settings.h, app/src/ui_stream.h, app/src/ui_strings.c, app/src/ui_strings.h
See: https://github.com/trilitech/ledger-app-tezos-wallet/pull/220
=> add documentation for app operation and display functions

.github/workflows/build.yml
Needs https://github.com/trilitech/ledger-app-tezos-wallet/pull/243 to pass tests
=> Bump actions/upload-artifact and actions/download-artifact version to v4

tests/integration/touch/utils.py
- ledger-app-builder == 3.30.0
- ragger == 1.21.1
- speculos == 0.9.6
=> Bump `ledger-app-builder` version
