trilitech/ledger-app-tezos-wallet

- app/src/apdu.c
- app/src/apdu.h
- app/src/apdu_pubkey.c
- app/src/apdu_sign.c
- app/src/app_main.c
- app/src/compat.h
- app/src/exception.h
- app/src/globals.h
- app/src/keys.c
- app/src/keys.h
- app/src/ui_stream.c
- app/src/ui_stream.h
This invovles getting rid of all of the setjmp(3)/longjmp(3) and percolating errors around in the more idiomatic C way.  We define a set of macros to make it all a little easier to keep track of.
> Rototill to move to using lib_standard_app's io model

- app/src/globals.c
- app/src/globals.h
- app/src/ui_home.c
- app/src/ui_home_nbgl.c
- app/src/ui_settings.c
required to persist settings (currently just blindsiging toggle) between user-runs of the app.
The following works with the inclusion of this PR:
- Run the app on a physical device (e.g. nanos)
- Open the app
- enable blindsigning
- exit the app
- Re-open the app. Blindsigning should still be enabled
To build & run the app on the nanos, connect & unlock the nanos, and then run:
```
docker run --rm -ti --user "$(id -u):$(id -g)" --privileged -v "/dev/bus/usb:/dev/bus/usb" -v "$(realpath .):/app" ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
cd app
make load
```
and follow the prompts on the nanos
> app: store settings in NVM

- app/src/apdu_pubkey.c
- app/src/apdu_sign.c
- app/src/parser/formatting.c
- app/src/parser/formatting.h
- app/src/parser/num_parser.c
- app/src/parser/operation_parser.c
We solve a buffer overflow here. In these commits, we:
- add an output buffer size parameter to most `tz_format_*()` functions. This allows us to fail if we are going to overflow any buffers. The current documentation in headers says that it is the caller's responsibility to ensure that the buffers are large enough to contain the formatted string, but without some sort of verification it is too easy to make an error. Now, we doublecheck,
- we fix some sizes that were actually incorrect, and
- the macro `TZ_BASE58CHECK_BUFFER_SIZE()` did not evaluate to the correct number, because the macro `TZ_BASE58_BUFFER_SIZE()`  did not put brackets to ensure that order of operations did not fail. As a drive by, I used `_` in front of each argument in the macros to make it less likely that the …
> Fix formats

- app/src/ui_stream_nbgl.c
- tests/integration/stax/test_sign_execute_outbox_messages_skip.py
- tests/integration/stax/utils.py
Currently, after a skip during a signing request on stax, the user is able to sign even though all the apdus have not yet been received.
To avoid this, this MR adds a spinner until all the apdus have been received.
> Stax: add a spinner on skip

- .github/workflows/build.yml
- tests/integration/check_section_text.py
fixes #43 
The `$URL/events?currentscreenonly=true` service does not seem to correspond to what is actually on the screen.
Fortunately, the `$URL/events` service allows the recovery of everything that has been displayed, including what has been lost by `$URL/events?currentscreenonly=true`.
> Re-enable nanox generated tests

- tests/integration/test_runtime.sh
This is ultimately due to assuming `send_apdu` is synchronous, when in fact it runs in the background. This can lead to `expect_apdu_return` doing its check before the apdu call is complete, unless intermediate steps are in place
> tests: temporarily fix flaky pk tests

- .github/workflows/build.yml
- .github/workflows/codeql_checks.yml
- .github/workflows/coding_style_checks.yml
- .github/workflows/guidelines_enforcer.yml
- .github/workflows/swap.yml
We will use the `develop` branch for the bootstrapping of the baking app, to avoid churn while the wallet audit is happening
fixes #74
> CI: run jobs on develop branch

- app/src/ui_settings.c
- app/src/ui_stream.c
- app/src/ui_stream.h
Change the back settings screen icon to back arrow
Does not fix the `NANOSP` and `NANOX`, it will be done here: #80 
- fixes #81
> Change the back settings screen icon to back arrow

- app/src/apdu_pubkey.c
The Ledger developers informed us that we do not need to do this.
We were informed that this is "probably" an unnecessary check. We should make sure that we agree before we put this in.
> apdu_pubkey.c: don't check if we are locked

- .github/workflows/swap.yml
In order to enable changes to be made to the `palmer/functori/add-new-tezos-app-swap-tests` branch of the `spalmer25/app-exchange` repository without breaking the tests.
> Swap: Change branche pointer for commit pointer in swap job

- app/src/apdu_pubkey.c
- app/src/apdu_sign.c
- app/src/app_main.c
- app/src/globals.h
- app/src/handle_swap.c
- app/src/keys.c
- app/src/keys.h
- app/src/ui_stream_nbgl.c
- tests/integration/nano/test_provide_tz1_bip25519_pk.sh
fixes #108. 
Add pk to globals to save repeated computation of pk. added pub key to global.key in union with apdu as apdu.hash/sign is not used concurrently with pk in any operation.
> wallet: Add public key to globals

- app/src/exception.h
- app/src/globals.h
- app/src/ui_stream.c
- app/src/ui_stream.h
- app/src/ui_stream_nbgl.c
- app/src/ui_strings.c
- app/src/ui_strings.h
progress towards:
- #91 
- #23 
We are trying to update STAX to allow multiple values per screen. Doing so in the same method  as `ui_stream.c` would be very wasteful though - as stax values could be _up to_ well over 120+ bytes per value on a single screen, but most of the time we don't need anything close to that (e.g. `Fee` field etc).
Therefore, we compress all strings in memory, into a 'sudo'-ring-buffer, to allow more efficient use memory, for screens (on all devices) that consume fewer bytes than are pre-allocated arrays in the `global.screens[bucket]`.
This actually results in a saving of well over 30bytes on the nanos, and with the current parameters, over 250-300bytes on the nanosp/x. It will theoretically save potential 1-2 kilobytes on the Stax, if we implement history there …
> ui_strings: a ring buffer for screen text

- app/src/ui_strings.c
Left over from a bad rebase/commit shuffle.
The following now works:
```
make clean
make app_nanos_dbg.tgz
docker run --rm -it --entrypoint /bin/bash -v $(pwd):/app --network host ledger-app-tezos-integration-tests
cd /app
git config --global --add safe.directory /app
./tests/integration/nano/test_tz2_sign_micheline_basic.py --device nanos --port 5000 --display headless --vnc-port 41000 --app app/bin/app.elf
```
> ui_strings: global not static

- app/src/ui_stream.c
When pushing the first screen - we will always be to the same bucket that `s->current` points to.
> nano: fix misleading warning on first screen

- app/src/apdu_sign.c
- app/src/apdu_sign.h
- app/src/ui_stream_nbgl.c
- tests/integration/stax/utils.py
Previously, the skip button was removed. We now remove the remaining code related to that feature
> stax: remove skip code

- .github/workflows/guidelines_enforcer.yml
Follow up suggestion from Ledger, the option will be deprecated at some point.
Related #149
> CI: remove unneeded lines from reusable workflows

- app/src/parser/operation_parser.c
- tests/unit/ctest/tests_parser.c
Since `field_name` are not operation fields, they do not need to be marked as complex.
This MR resets the `is_field_complex` field when there are no more fields to parse for an operation.
> Parser: fix is_field_complex

- app/Makefile
APPLICATION_FLAG_GLOBAL_PIN, APPLICATION_FLAG_BOLOS_SETTINGS
needs to update the ledger-app-database for app permission flags.
> Remove unused Ledger flags

- app/src/apdu.c
- app/src/apdu.h
- app/src/apdu_sign.c
- app/src/globals.h
- app/src/keys.c
- app/src/keys.h
- app/src/parser/operation_parser.c
- app/src/parser/operation_state.h
- app/src/ui_stream.c
- app/src/ui_stream.h
- app/src/ui_stream_nbgl.c
- app/src/ui_strings.c
- tests/integration/test_runtime.sh
> Address audit report comments

- app/src/handle_swap.c
- app/src/parser/micheline_state.h
- app/src/parser/operation_parser.c
- app/src/parser/parser_state.h
- app/src/ui_strings.c
> CodeQL: fix some code quality

- app/src/apdu_sign.h
- app/src/globals.h
- app/src/parser/parser_state.h
- app/src/ui_stream.h
- app/src/ui_strings.h
At many times, when some fields were added on some structures, two tests were failing on **NanoS**:
- `test_tz3_sign_micheline_basic`
- `test_tz2_sign_micheline_basic.`
This is caused by an already known issue that signing with _tz2_ and _tz3_ needs more memory than for _tz1_.
This PR reduce the memory space required for the `global` by reordering structures fields.
Gain of `32*sizeof(uint8_t)` memory space.
> Reduce the global struct size

- app/src/apdu_sign.c
- app/src/format.h
Some feedbacks from Ledger's audit warn for some fixes/improvements:
- A wrong assertion in the `get_blindsign_type` function
- A missing header guard to the `format.h` file
> Audit feedback fixes (v3.0.5)
